### ISSUE TITLE
Enable Travis CI integration

### ISSUE THREAD

**Issue by guusdk** [tking/JSTUN#10]
Travis is a free continuous integration platform, that integrates easily with Github-based Maven projects (among many, many others). By using it, every pull request would be automatically build by Travis, which will provide feedback on compile and/or test failures.

Setting it up is trivial, but requires you to allow Travis some permissions on this repository. After that, a single textfile is to be added to the root of the project. The textfile should be named `.travis.yml` (starts with a dot), and should contain this single line:

`
language: java
`

There's a wealth of further information available, but this is the absolute beginners guide to Travis:  https://docs.travis-ci.com/user/for-beginners

**Comment by tking** [comment]
I integrated Travis CI as requested. This is a really good idea! Thanks for this proposal!
This is the result (looks good from my point of view :-)).

Results :
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0

**Comment by tking** [comment]
You probably know it, however, here the link to CI gui:
https://travis-ci.org/tking/JSTUN
